[project]
name = "rspace-mcp"
version = "0.1.0"
description = "RSpace MCP server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.9.2",
    "rspace-client>=2.6.1",
]
